#check root env-example before running
services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always  

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090" 
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml   


  api-gateway: 
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./api-gateway/.env  
    environment:
      - "REDIS_HOST=redis"  
      - "REDIS_PORT=6379"  
      - "AUTH_SERVICE_URL=http://auth-service:8081"
      - "FLIGHT_SERVICE_URL=http://flight-service:8084"
    depends_on:
      - redis


  auth-service:
    build: 
      context: ./auth-service
      dockerfile: Dockerfile
    expose:
      - 8081
    env_file:
     - ./auth-service/.env
    environment:
      DB_URL: ${AUTH_DB}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    
    depends_on:
      - redis

  flight-service:
    build:
      context: ./flight-service
      dockerfile: Dockerfile    
    expose:
      - 8084
    env_file:
      - ./flight-service/.env
    environment:
      DB_URL: ${flight_DB}
      REDIS_HOST: redis
      REDIS_PORT: 6379

         

    depends_on:
     - redis  

    
